name: Release SXAC

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install --no-install-recommends -y gcc libc-dev libx11-dev libxtst-dev make
      - name: Build
        run: make
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: sxac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
